# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_last_edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last edited')),
            ],
        ),
        migrations.CreateModel(
            name='PlayInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kexp_play_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='play_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.PlayInstance'),
        ),
    ]
