# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playinstance',
            name='airdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='airdate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
