# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20190602_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
